### ISSUE TITLE
Problem with Windows 10 Fall Creator Update

### ISSUE THREAD

**Issue by duyvu1311** [djm34/ccminer-msvc2015#22]
When I updated Windows to Fall Creator Update version, it seems Ccminer causes my system lag. No problem when running EWBF's CUDA Zcash miner. Driver has been updated to the latest version (v387.92).Please, help me fix this issue. My system detail: 6x GPU 1060 3GB. CPU Intel G3930, 4GB of RAM.
Thanks!

**Update: This issue happens with Lyra2Z algo only.**

P/S:
I think the author should develop another close-source version with devfee, so the miner will be better and updated sooner if any issue occurs.

**Comment by djm34** [comment]
lyra2z uses lots of ressource, so if windows fall create update on its side use more ressource too, it can cause lags. My advice is to use the integrated gpu rather than the discrete gpu (the nvidia card) to plug your monitor. This way you won't lag anymore.
Another alternative is to reduce the intensity.
